name: CI

on: [push]

permissions:
  id-token: write        # КРИТИЧНО: разрешает workflow запросить OIDC-токен
  contents: read         # checkout читает код

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::802421411869:role/github-actions-ecr-push
          aws-region: eu-central-1

      - name: Login to Amazon ECR
        id: ecr-login
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: 802421411869.dkr.ecr.eu-central-1.amazonaws.com/git-act:${{ github.sha }}